import type { Post } from '../types';

export const localPosts: Post[] = [
  {
    id: 'hello-world',
    title: 'Hello World',
    subtitle: 'My first post',
    summary: 'A simple introduction to this blog project.',
    content: 'This is my very first post. Excited to be here!',
    featured_image: 'https://images.unsplash.com/photo-1499750310107-5fef28a66643?auto=format&fit=crop&w=1200&q=80',
    category: 'General',
    created_at: '2026-07-01',
    updated_at: '2026-07-01',
    tags: ['Next.js', 'React'],
    comments: [],
    Author: [],
    user: { id: '1', first_name: 'Demo' },
  },
  {
    id: 'learning-nextjs',
    title: 'Learning Next.js',
    subtitle: 'Notes on my journey',
    summary: 'Some notes about routing, server components, and React.',
    content: 'Next.js adds routing, server components, and more on top of React.',
    featured_image: 'https://images.unsplash.com/photo-1516321497487-e288fb19713f?auto=format&fit=crop&w=1200&q=80',
    category: 'Tutorial',
    created_at: '2026-07-02',
    updated_at: '2026-07-02',
    tags: ['Next.js'],
    comments: [],
    Author: [],
    user: { id: '2', first_name: 'Demo' },
  },
  {
    id: 'flexbox-tips',
    title: 'Flexbox Tips',
    subtitle: 'Things I wish I knew earlier',
    summary: 'Useful tips for controlling layout with Flexbox.',
    content: 'Use flex-direction to control layout, and gap for spacing between items.',
    featured_image: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1200&q=80',
    category: 'CSS',
    created_at: '2026-07-03',
    updated_at: '2026-07-03',
    tags: ['CSS'],
    comments: [],
    Author: [],
    user: { id: '3', first_name: 'Demo' },
  },
];
